name: Researcher

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/research')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/research')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '/research')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '/research') || contains(github.event.issue.title, '/research'))) ||
      (github.event_name == 'pull_request' && (github.event.action == 'opened' || contains(github.event.pull_request.body, '/research')))
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Researcher
        id: research
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GH_PAT }}
          trigger_phrase: "/research"
          allowed_tools: Bash   
          custom_instructions: |
            1. Research the defined subject
            2. Only use the specs specified by the user.
            3. If no specs are specified ask the user to clarify before proceeding.
            4. Use the json schema specs to extract information from the research as json
            5. Save the extractor artifacts to ./research/<subject>/<spec>.json
            6. Use the collected json to generate a markdown formatted report
            7. Save the report to ./research/<subject>/report.md
